@startuml

participant MixerBasedSystemControl as mix
participant MixerBasedSystemControlSettings as mixset
participant AWG as awg
participant SignalGenerator as sig

[-> mix ++: setup (frequencies)
note right of mix: min_freq = minimum in frequencies
mix -> mixset ++: get_awg_frequency ()
mixset -> awg ++: get_frequency ()
return awg_frequency
return awg_frequency

mix -> mixset ++: set_sig_frequency (min_freq + awg_frequency)
mixset -> sig ++: set_frequency (min_freq + awg_frequency)
note right of sig: frequency = min_freq + awg_frequency
return
return

mix -> mixset ++: get_sig_frequency ()
mixset -> sig ++: get_frequency ()
return sig_frequency
return sig_frequency

mix -> mixset ++: set_awg_multiplexing_frequencies (sig_frequency - frequencies)
mixset -> awg ++: set_multiplexing_frequencies (sig_frequency - frequencies)
note right of awg: multiplexing_frequencies = sig_frequency - frequencies
return
return

mix -> mixset ++: setup_awg ()
mixset -> awg ++: setup ()
note right of awg #E68AA3: AWG setup
return
return

mix -> mixset ++: setup_sig ()
mixset -> sig ++: setup ()
note right of sig #E68AA3: SignalGenerator setup
return
return

[<-- mix


@enduml