@startuml

participant SimulatedSystemControl as sim
participant SimulatedSystemControlSettings as simset
queue Qutip as qutip

[-> sim ++: setup (frequencies)
sim -> simset ++: get_nsteps ()
return nsteps
sim -> simset ++: get_store_states ()
return store_states

sim -> qutip ++: create_options (nsteps, store_states)
return result_options
note right of sim: self.options = result_options

return

@enduml
