repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.11.2"
    hooks:
      - id: mypy
        args: ["--no-strict-optional", "--ignore-missing-imports", "--config-file=pyproject.toml"]
        additional_dependencies: []

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-ruff

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.0
    hooks:
      # - id: nbqa-ruff
      #   args: [ --fix ]
      - id: nbqa-mypy

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.40.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
