@startuml

participant QBloxClusterController as qblox
participant Cluster as dev
participant Instrument as instr

[-> qblox ++: set_device_to_all_modules ()
loop module, slot_id in zip (self.modules, self.connected_modules_slot_ids)
    qblox -> dev ++: get_modules [slot_id]
    return modules [slot_id]
    qblox -> instr ++: module.set_device (modules [slot_id])
    note right of instr: module.device = self.device.modules [slot_id]
    return
end
return

@enduml
