@startuml

participant RXGate as gaterx
participant HardwareGateSettings as hardset

[-> gaterx ++: translate (gate ,master_amplitude_gate, master_duration_gate)
gaterx -> gaterx: parameters (master_amplitude_gate, master_duration_gate)
activate gaterx #7F1CDB
note right of gaterx: HardwareGate parameters
return x_params
note right of gaterx: theta = gate.parameters
gaterx -> gaterx: normalize_angle (theta)
activate gaterx #7F1CDB
note right of gaterx: angle %= 2 * pi
opt angle > pi
    note right of gaterx: angle -= 2 * pi
end
return theta
note right of gaterx: amplitude = (theta / pi) * x_params.amplitude
alt theta >= 0
    note right of gaterx: phase = x_params.phase
else
    note right of gaterx: phase = x_params.phase + pi
end

gaterx -> hardset **: HardwareGateSettings (amplitude, phase, x_params.duration, x_params.shape)
activate hardset
return hardware_gate_settings
return hardware_gate_settings

@enduml