@startuml

participant Instrument as instr
participant InstrumentSettings as instrset

[-> instr ++: set_parameter (parameter, value)
instr -> instrset ++: set_parameter (parameter, value)
note right of instrset #C2A5DC: DDBBElement set_parameter
return
opt hasattr(self, "device")
    instr -> instr: setup ()
    activate instr #7F1CDB
    note right of instr #E68AA3: Instrument setup
    return
end
[<-- instr
@enduml
