@startuml

header QiliLab version 0.5.4
title Experiment execute Sequence Diagram

actor User as usr
participant Experiment as exp
participant ExperimentSettings as expset
participant Results as results
participant Execution as exe
participant BusesExecution as busesexe
participant RemoteAPI as remote_api
participant API as api
participant LivePlot as liveplot

activate exp
usr -> exp: execute
exp -> remote_api ++: __enter__()
opt self.connection is not None
      remote_api -> api ++: block_device_id (self.device_id)
      return
      note right of remote_api: self._blocked_device = True
end
return

exp -> exp: create_folder ()
activate exp #7F1CDB
return result_path
note right of exp: path = result_path
exp -> exp: create_results_file (path)
activate exp #7F1CDB 
return
exp -> exp: dump_experiment_data (path)
activate exp #7F1CDB
return

exp -> exe ++: get_num_sequences ()
exe -> busesexe ++: get_num_sequences ()
return num_sequences
return num_sequences

exp -> liveplot **: LivePlot (self.remote_api, self.loops, self.plot_y_label, num_sequences)
activate liveplot
note right of liveplot #C2A5DC: LivePlot \ncreation
return plot

exp -> expset ++: get_software_average ()
return software_average
exp -> results **: Results (software_average, num_sequences, self.loops)
activate results
note right of results #C2A5DC: Results \ncreation
return results

exp -> exe ++: __enter__()
note right of exe #C2A5DC: Execution __enter__ ()
return

exp -> exp: recursive_loops (self.loops, results, path, plot)
activate exp #7F1CDB
note right of exp #C2A5DC: Experiment recursive_loops ()
                  
return results
exp -> exe ++: __exit__()
note right of exe #C2A5DC: Execution __exit__ ()
return

exp -> remote_api ++: __exit__()
opt self.connection is not None AND self._blocked_device
      remote_api -> api ++ : release_device (device_id)
      return
      note right of remote_api: self._blocked_device = False
end
return

usr <-- exp: results            
@enduml