@startuml

participant Keithley2600 as kei
participant Keithley2600Settings as set
participant Keithley2600Driver as dri

[-> kei ++: setup()
kei -> set ++: get_max_current ()
return max_current
kei -> dri ++: set_smua_limiti (max_current)
note right of dri: smua.limiti = max_current
return
kei -> set ++: get_max_voltage ()
return max_voltage
kei -> dri ++: set_smua_limitv (max_voltage)
note right of dri: smua.limitv = max_voltage
return
return

@enduml
