@startuml

participant MixerBasedSystemControl as mix
participant MixerBasedSystemControlSettings as mixset
participant SignalGenerator as sig

[-> mix ++: start ()
mix -> mixset ++: start_sig ()
mixset -> sig ++: start ()
note right of sig #E68AA3: SignalGenerator start
return
return
[<-- mix


@enduml
