@startuml

participant IGate as gatei

[-> gatei ++: translate (gate ,master_amplitude_gate, master_duration_gate)
gatei -> gatei: parameters (master_amplitude_gate, master_duration_gate)
activate gatei #7F1CDB
note right of gatei: HardwareGate parameters
return hardware_gate_settings
return hardware_gate_settings

@enduml