software_average: 1
num_schedules: 1
shape:
- 31
loops:
- alias: Drag(1)
  parameter: amplitude
  values:
  - 0
  - 0.00833333
  - 0.0166667
  - 0.025
  - 0.0333333
  - 0.0416667
  - 0.05
  - 0.0583333
  - 0.0666667
  - 0.075
  - 0.0833333
  - 0.0916667
  - 0.1
  - 0.108333
  - 0.116667
  - 0.125
  - 0.133333
  - 0.141667
  - 0.15
  - 0.158333
  - 0.166667
  - 0.175
  - 0.183333
  - 0.191667
  - 0.2
  - 0.208333
  - 0.216667
  - 0.225
  - 0.233333
  - 0.241667
  - 0.25
  loop:
  channel_id:
results:
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 33.54630610649731
        path1:
        - -19.275608988764045
      threshold:
      - 0.2194
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 33.44339775280899
        path1:
        - -19.261704152418172
      threshold:
      - 0.225
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 32.379233512457255
        path1:
        - -21.26761211529067
      threshold:
      - 0.2706
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 30.240299853444064
        path1:
        - -24.042995603321934
      threshold:
      - 0.3436
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 27.113896922325353
        path1:
        - -28.592570688812895
      threshold:
      - 0.4636
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 24.566652173913045
        path1:
        - -32.30613825109917
      threshold:
      - 0.5564
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 21.907137469467514
        path1:
        - -36.131165608207134
      threshold:
      - 0.6572
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 20.363796971177333
        path1:
        - -38.36964347826087
      threshold:
      - 0.7174
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 19.88161143136297
        path1:
        - -38.828510796287254
      threshold:
      - 0.7302
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 20.267636345872006
        path1:
        - -38.37820322423058
      threshold:
      - 0.7158
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 21.69922686858818
        path1:
        - -36.424181729360036
      threshold:
      - 0.669
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 23.3730438690767
        path1:
        - -33.73275329750855
      threshold:
      - 0.5968
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 25.502133561309233
        path1:
        - -29.891714313629702
      threshold:
      - 0.505
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 28.917942550073278
        path1:
        - -24.98999443087445
      threshold:
      - 0.3806
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 31.480029018075232
        path1:
        - -20.73387972642892
      threshold:
      - 0.266
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 34.002716560820716
        path1:
        - -18.120424425989253
      threshold:
      - 0.1856
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 35.53178935026869
        path1:
        - -15.623802442598926
      threshold:
      - 0.1356
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 36.461945285784076
        path1:
        - -14.49948695652174
      threshold:
      - 0.1042
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 35.77196570591109
        path1:
        - -15.191374401563262
      threshold:
      - 0.1252
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 34.540900048851974
        path1:
        - -17.26972554958476
      threshold:
      - 0.1724
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 32.914767855398146
        path1:
        - -20.187899951148022
      threshold:
      - 0.2448
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 30.488812212994624
        path1:
        - -23.616056277479238
      threshold:
      - 0.3342
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 28.201154665363948
        path1:
        - -27.01360175867123
      threshold:
      - 0.4184
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 25.655965510503176
        path1:
        - -31.160861651196875
      threshold:
      - 0.5234
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 24.201330239374695
        path1:
        - -33.118034782608696
      threshold:
      - 0.5732
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 22.158465266243283
        path1:
        - -36.33510102589155
      threshold:
      - 0.6502
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 20.636924572545187
        path1:
        - -37.7943093307279
      threshold:
      - 0.7012
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 20.398458133854422
        path1:
        - -38.95039804592086
      threshold:
      - 0.7238
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 19.525226380068393
        path1:
        - -39.73109447972643
      threshold:
      - 0.7498
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 19.378007816316558
        path1:
        - -39.56797606253053
      threshold:
      - 0.7482
      avg_cnt:
      - 5000.0
- name: qblox
  integration_lengths:
  - 2000
  qblox_raw_results:
  - scope:
      path0:
        data: []
        out-of-range: false
        avg_cnt: 0
      path1:
        data: []
        out-of-range: false
        avg_cnt: 0
    bins:
      integration:
        path0:
        - 19.085087054225696
        path1:
        - -39.99365461651197
      threshold:
      - 0.7594
      avg_cnt:
      - 5000.0
