@startuml

participant HardwareGate as hw
participant HardwareGateSettings as set

[-> hw ++: parameters (master_amplitude_gate, master_duration_gate)
hw -> hw: apply_master_values_to_hardware_gate_settings (settings, master_amplitude_gate, master_duration_gate)
activate hw #7F1CDB
hw -> set ++: get_amplitude ()
return amplitude
hw -> hw: use_master_value_when_variable_is_referencing_master_name (amplitude, master_amplitude_gate, master_duration_gate)
activate hw #E6033F
note right of hw #C2A5DC: HardwareGate use master value
return result_amplitude
hw -> set ++: set_amplitude (result_amplitude)
note right of set: amplitude = result_amplitude
return

hw -> set ++: get_duration ()
return duration
hw -> hw: use_master_value_when_variable_is_referencing_master_name (duration, master_amplitude_gate, master_duration_gate)
activate hw #E6033F
note right of hw #C2A5DC: HardwareGate use master value
return result_duration
hw -> set ++: set_duration (result_duration)
note right of set: duration = result_duration
return

return settings
return settings

@enduml
