@startuml

participant QBloxClusterController as qblox
participant Cluster as dev

[-> qblox ++: initialize_device ()
qblox -> dev **: Cluster (name = self.name.value self.id, identifier = self.address)
activate dev
return device
return

@enduml