@startuml

participant SGS100A_Controller as sgs
participant RohdeSchwarzSGS100A as dev

[-> sgs ++: initialize_device ()
sgs -> dev **: RohdeSchwarzSGS100A ("self.name.value"\n"self.id","TCPIP0:: self.address:: inst0::INSTR")
activate dev
return device
return

@enduml