@startuml

participant XYGate as gatexy
participant HardwareGateSettings as hardset

[-> gatexy ++: translate (gate ,master_amplitude_gate, master_duration_gate)
gatexy -> gatexy: parameters (master_amplitude_gate, master_duration_gate)
activate gatexy #7F1CDB
note right of gatexy: HardwareGate parameters
return x_params
note right of gatexy: theta, phi = gate.parameters
gatexy -> gatexy: normalize_angle (theta)
activate gatexy #7F1CDB
note right of gatexy: angle %= 2 * pi
opt angle > pi
    note right of gatexy: angle -= 2 * pi
end
return theta
note right of gatexy: amplitude = (theta / pi) * x_params.amplitude
alt theta >= 0
    note right of gatexy: phase = phi % (2 * pi)
else
    note right of gatexy: phase = (phi + pi) % (2 * pi)
end

gatexy -> hardset **: HardwareGateSettings (amplitude, phase, x_params.duration, x_params.shape)
activate hardset
return hardware_gate_settings
return hardware_gate_settings

@enduml