@startuml

participant MGate as gatem

[-> gatem ++: translate (gate ,master_amplitude_gate, master_duration_gate)
gatem -> gatem: parameters (master_amplitude_gate, master_duration_gate)
activate gatem #7F1CDB
note right of gatem: HardwareGate parameters
return hardware_gate_settings
return hardware_gate_settings

@enduml