elements:
  - id_: 0
    category: bus
    subcategory: control
    system_control:
      id_: 0
      category: system_control
      subcategory: simulated_system_control  # unique name
      qubit: csfq4jj
      frequency: 2085540698
      driving_hamiltonian: zport
      resolution: 0.01  # ns
      nsteps: 100000000
      store_states: false
      dimension: 10
    target:
      id_: 0
      name: qubit
      category: qubit
      pi_pulse_amplitude: 1
      pi_pulse_duration: 100
      pi_pulse_frequency: 100000000.0
      qubit_frequency: 3544000000.0
      min_voltage: 950
      max_voltage: 1775
