@startuml

participant XGate as gatex

[-> gatex ++: translate (gate ,master_amplitude_gate, master_duration_gate)
gatex -> gatex: parameters (master_amplitude_gate, master_duration_gate)
activate gatex #7F1CDB
note right of gatex: HardwareGate parameters
return hardware_gate_settings
return hardware_gate_settings

@enduml