# Copyright 2023 Qilimanjaro Quantum Tech
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from copy import deepcopy
from typing import TYPE_CHECKING, overload

import numpy as np

from qililab.qprogram.blocks.block import Block
from qililab.qprogram.calibration import Calibration
from qililab.qprogram.crosstalk_matrix import CrosstalkMatrix, FluxVector
from qililab.qprogram.decorators import requires_domain
from qililab.qprogram.operations import (
    Acquire,
    AcquireWithCalibratedWeights,
    Measure,
    MeasureReset,
    MeasureWithCalibratedWaveform,
    MeasureWithCalibratedWaveformWeights,
    MeasureWithCalibratedWeights,
    Play,
    PlayWithCalibratedWaveform,
    ResetPhase,
    SetFrequency,
    SetGain,
    SetMarkers,
    SetOffset,
    SetPhase,
    SetTrigger,
    Sync,
    Wait,
    WaitTrigger,
)
from qililab.qprogram.structured_program import StructuredProgram
from qililab.qprogram.variable import Domain
from qililab.waveforms import Arbitrary, IQPair, Waveform
from qililab.yaml import yaml

if TYPE_CHECKING:
    from qililab.extra.quantum_machines.qprogram.quantum_machines_compiler import QuantumMachinesCompilationOutput
    from qililab.qprogram.qblox_compiler import QbloxCompilationOutput
    from qililab.qprogram.qdac_compiler import QdacCompilationOutput


class QProgramCompilationOutput:
    """Class representing the output information generated by qprogram compiler."""

    def __init__(
        self,
        qblox: "QbloxCompilationOutput | None" = None,
        qdac: "QdacCompilationOutput | None" = None,
        quantum_machines: "QuantumMachinesCompilationOutput | None" = None,
    ):
        self.qblox = qblox
        self.qdac = qdac
        self.quantum_machines = quantum_machines


@yaml.register_class
class QProgram(StructuredProgram):
    """QProgram is a hardware-agnostic pulse-level programming interface for describing quantum programs.

    This class provides an interface for building quantum programs,
    including defining operations, managing variables, and handling blocks.
    It contains methods for creating, manipulating and controlling
    the execution flow of quantum operations within a program.

    Examples:

        The following example illustrates how to define a Rabi sequence using QProgram.

        .. code-block:: python3

            from qililab import QProgram, Domain, IQPair, Square

            qp = QProgram()

            # Pulse used for changing the state of qubit
            control_wf = IQPair.DRAG(amplitude=1.0, duration=40, num_sigmas=4.0, drag_correction=-2.5)

            # Pulse used for exciting the resonator for readout
            readout_wf = IQPair(I=Square(amplitude=1.0, duration=400), Q=Square(amplitude=0.0, duration=400))

            # Weights used during integration
            weights = IQPair(I=Square(amplitude=1.0, duration=2000), Q=Square(amplitude=1.0, duration=2000))

            # Declare a variable
            gain = qp.variable(label="gain", domain=Domain.Voltage)

            # Loop the variable's value over the range [0.0, 1.0]
            with qp.for_loop(variable=gain, start=0.0, stop=1.0, step=0.01):
                # Change the gain output of the drive_bus
                qp.set_gain(bus="drive_bus", gain=gain)

                # Play the control pulse
                qp.play(bus="drive_bus", waveform=control_wf)

                # Sync the buses
                qp.sync()

                # Measure
                qp.measure(bus="readout_bus", waveform=readout_wf, weights=weights)

    """

    def __init__(self) -> None:
        super().__init__()
        self.qblox = self._QbloxInterface(self)
        self.quantum_machines = self._QuantumMachinesInterface(self)
        self.qdac = self._QdacInterface(self)

    def __str__(self) -> str:
        def traverse(block: Block):
            string_elements = []
            for element in block.elements:
                string_elements.append(f"{type(element).__name__}:\n")
                for attr_name in vars(element):
                    # ignore uuid, variables. elements, waveforms and weights are handled separately
                    if attr_name in ("_uuid", "variable", "elements", "waveform", "weights"):
                        continue

                    attr_value = getattr(element, attr_name)
                    # Handle UUID checking and append to string_elements
                    if "UUID" not in str(attr_value):
                        string_elements.append(f"\t{attr_name}: {attr_value}\n")
                    else:
                        string_elements.append(f"\t{attr_name}: None\n")  # pragma: no cover

                if isinstance(element, Block):
                    # handle blocks
                    for string_element in traverse(element):
                        string_elements.append(f"\t{string_element}")

                # if not a block, it is assumed that element is type Operation
                if hasattr(element, "waveform"):
                    waveform_string = (
                        [f"\tWaveform {type(element.waveform).__name__}:\n"]
                        + [f"\t\t{array_line}\n" for array_line in str(element.waveform.envelope()).split("\n")]
                        if isinstance(element.waveform, Waveform)
                        else [f"\tWaveform I {type(element.waveform.I).__name__}:\n"]
                        + [f"\t\t{array_line}\n" for array_line in str(element.waveform.I.envelope()).split("\n")]
                        + [f"\tWaveform Q {type(element.waveform.Q).__name__}):\n"]
                        + [f"\t\t{array_line}\n" for array_line in str(element.waveform.Q.envelope()).split("\n")]
                    )
                    string_elements.extend(waveform_string)

                if hasattr(element, "weights"):
                    string_elements.append(f"\tWeights I {type(element.weights.I).__name__}:\n")
                    string_elements.extend(
                        [f"\t\t{array_element}\n" for array_element in str(element.weights.I.envelope()).split("\n")]
                    )
                    string_elements.append(f"\tWeights Q {type(element.weights.Q).__name__}:\n")
                    string_elements.extend(
                        [f"\t\t{array_element}\n" for array_element in str(element.weights.Q.envelope()).split("\n")]
                    )

            return string_elements

        return "".join(traverse(self._body))

    def has_calibrated_waveforms_or_weights(self) -> bool:
        """Checks if QProgram has named waveforms or weights. These need to be mapped before compiling to hardware-native code.

        Returns:
            bool: True, if QProgram has waveforms or weights that need to be mapped from calibration.
        """

        def traverse(block: Block):
            for element in block.elements:
                if isinstance(element, Block):
                    if traverse(element):
                        return True
                elif isinstance(
                    element,
                    (
                        PlayWithCalibratedWaveform,
                        AcquireWithCalibratedWeights,
                        MeasureWithCalibratedWaveform,
                        MeasureWithCalibratedWeights,
                        MeasureWithCalibratedWaveformWeights,
                    ),
                ):
                    return True
            return False

        return traverse(self.body)

    def with_bus_mapping(self, bus_mapping: dict[str, str]) -> "QProgram":
        """Returns a copy of the QProgram with bus mappings applied.

        Args:
            bus_mapping (dict[str, str]): A dictionary mapping old bus names to new bus names.

        Returns:
            QProgram: A new instance of QProgram with updated bus names.
        """

        def traverse(block: Block):
            for index, element in enumerate(block.elements):
                if isinstance(element, Block):
                    traverse(element)
                elif isinstance(element, MeasureReset):
                    bus = getattr(element, "bus")
                    control_bus = getattr(element, "control_bus")
                    if isinstance(bus, str) and bus in bus_mapping:
                        setattr(block.elements[index], "bus", bus_mapping[bus])
                    if isinstance(control_bus, str) and control_bus in bus_mapping:
                        setattr(block.elements[index], "control_bus", bus_mapping[control_bus])
                    new_latch_enabled = []
                    for bus in copied_qprogram.qblox.latch_enabled:
                        if bus in bus_mapping:
                            new_latch_enabled.append(bus_mapping[bus])
                        else:
                            new_latch_enabled.append(bus)
                    copied_qprogram.qblox.latch_enabled = new_latch_enabled

                    new_trigger_network_required = {}
                    for bus, value in copied_qprogram.qblox.trigger_network_required.items():
                        if bus in bus_mapping:
                            new_trigger_network_required[bus_mapping[bus]] = value
                        else:
                            new_trigger_network_required[bus] = value
                    copied_qprogram.qblox.trigger_network_required = new_trigger_network_required
                elif hasattr(element, "bus"):
                    bus = getattr(element, "bus")
                    if isinstance(bus, str) and bus in bus_mapping:
                        setattr(block.elements[index], "bus", bus_mapping[bus])
                elif hasattr(element, "buses"):
                    buses = getattr(element, "buses")
                    if isinstance(buses, list):
                        setattr(
                            block.elements[index],
                            "buses",
                            [bus_mapping[bus] if bus in bus_mapping else bus for bus in buses],
                        )

        # Copy qprogram so the original remain unaffected
        copied_qprogram = deepcopy(self)

        # Recursively traverse qprogram applying the bus mapping
        traverse(copied_qprogram.body)

        # Apply the mapping to buses property
        for bus in list(copied_qprogram.buses):
            if bus in bus_mapping:
                copied_qprogram.buses.remove(bus)
                copied_qprogram.buses.add(bus_mapping[bus])

        return copied_qprogram

    def with_calibration(self, calibration: Calibration):
        """Apply calibration to the operations within the QProgram.

        This method traverses the elements of the QProgram, replacing any
        named operations with the corresponding calibrated waveforms specified
        in the given Calibration instance.

        Args:
            calibration (Calibration): The calibration data to apply to the operations.

        Returns:
            QProgram: A new instance of QProgram with calibrated operations.
        """

        def traverse(block: Block):
            for index, element in enumerate(block.elements):
                if isinstance(element, Block):
                    traverse(element)
                elif isinstance(element, PlayWithCalibratedWaveform) and calibration.has_waveform(
                    bus=element.bus, name=element.waveform
                ):
                    waveform = calibration.get_waveform(bus=element.bus, name=element.waveform)
                    play_operation = Play(bus=element.bus, waveform=waveform, wait_time=element.wait_time)
                    block.elements[index] = play_operation
                elif isinstance(element, AcquireWithCalibratedWeights) and calibration.has_weights(
                    bus=element.bus, name=element.weights
                ):
                    weights = calibration.get_weights(bus=element.bus, name=element.weights)
                    acquire_operation = Acquire(bus=element.bus, weights=weights, save_adc=element.save_adc)
                    block.elements[index] = acquire_operation
                elif isinstance(element, MeasureWithCalibratedWaveform) and calibration.has_waveform(
                    bus=element.bus, name=element.waveform
                ):
                    waveform = calibration.get_waveform(bus=element.bus, name=element.waveform)
                    measure_operation = Measure(
                        bus=element.bus,
                        waveform=waveform,
                        weights=element.weights,
                        demodulation=element.demodulation,
                        save_adc=element.save_adc,
                    )
                    block.elements[index] = measure_operation
                elif isinstance(element, MeasureWithCalibratedWeights) and calibration.has_weights(
                    bus=element.bus, name=element.weights
                ):
                    weights = calibration.get_weights(bus=element.bus, name=element.weights)
                    measure_operation = Measure(
                        bus=element.bus,
                        waveform=element.waveform,
                        weights=weights,
                        demodulation=element.demodulation,
                        save_adc=element.save_adc,
                    )
                    block.elements[index] = measure_operation
                elif (
                    isinstance(element, MeasureWithCalibratedWaveformWeights)
                    and calibration.has_waveform(bus=element.bus, name=element.waveform)
                    and calibration.has_weights(bus=element.bus, name=element.weights)
                ):
                    waveform = calibration.get_waveform(bus=element.bus, name=element.waveform)
                    weights = calibration.get_weights(bus=element.bus, name=element.weights)
                    measure_operation = Measure(
                        bus=element.bus,
                        waveform=waveform,
                        weights=weights,
                        demodulation=element.demodulation,
                        save_adc=element.save_adc,
                    )
                    block.elements[index] = measure_operation

        copied_qprogram = deepcopy(self)
        traverse(copied_qprogram.body)
        return copied_qprogram

    def with_crosstalk(self, crosstalk: CrosstalkMatrix):
        """Apply crosstalk compensation to the qprogram flux buses.

        This method traverses the elements of the QProgram, replacing any
        Play or Offset instances by the compensated envelope or offset for
        all flux buses.

        Args:
            crosstalk (CrosstalkMatrix): Crosstalk matrix class.

        Returns:
            QProgram: A new instance of QProgram with calibrated crosstalk.
        """

        def traverse(block: Block):
            element_list = []
            flux_vector = FluxVector()
            flux_vector.set_crosstalk(crosstalk)  # type: ignore

            for i, element in enumerate(block.elements):
                if isinstance(element, (Play, SetOffset)) and element.bus in crosstalk.matrix.keys():  # type: ignore
                    element_list.append(i)
                    flux_vector = handle_flux_vector(flux_vector=flux_vector, element=element)

                if isinstance(element, Block):
                    traverse(element)

            block = handle_crosstalk_element(block=block, element_list=element_list, flux_vector=flux_vector)

        def handle_flux_vector(flux_vector: FluxVector, element: Play | SetOffset):
            if isinstance(element, Play):
                if isinstance(element.waveform, Waveform):
                    envelope = element.waveform.envelope()
                elif isinstance(element.waveform, IQPair):
                    envelope = element.waveform.I.envelope()
            elif isinstance(element, SetOffset):  # square with same dimension as play
                envelope = element.offset_path0  # type: ignore

            if (
                isinstance(envelope, np.ndarray)
                and isinstance(flux_vector[element.bus], np.ndarray)
                and flux_vector[element.bus].shape != envelope.shape  # type: ignore
            ):
                raise ValueError("qp.play elements must have the same size.")
            flux_vector[element.bus] = envelope
            return flux_vector

        def handle_crosstalk_element(block: Block, element_list: list[int], flux_vector: FluxVector):
            if element_list:
                elements = []
                for ii, element_idx in enumerate(element_list):
                    elements.append(block.elements.pop(element_idx - ii))

                play_elements = [element for element in elements if isinstance(element, Play)]
                if play_elements:
                    dwell, delay, repetitions = (
                        play_elements[0].dwell,
                        play_elements[0].delay,
                        play_elements[0].repetitions,
                    )

                for bus in flux_vector.bias_vector.keys():
                    if isinstance(flux_vector.bias_vector[bus], float):
                        offset = SetOffset(bus, flux_vector.bias_vector[bus])  # type: ignore
                        block.elements.insert(element_list[0], offset)
                    elif isinstance(flux_vector.bias_vector[bus], np.ndarray) or isinstance(
                        flux_vector.bias_vector[bus], list
                    ):
                        play = Play(
                            bus,
                            Arbitrary(flux_vector.bias_vector[bus]),  # type: ignore
                            dwell=dwell,
                            delay=delay,
                            repetitions=repetitions,
                        )
                        block.elements.insert(element_list[0], play)

        copied_qprogram = deepcopy(self)
        traverse(copied_qprogram.body)
        return copied_qprogram

    @overload
    def play(
        self,
        bus: str,
        waveform: Waveform | IQPair,
    ) -> None:
        """Play a single waveform or an I/Q pair of waveforms on the bus.

        Args:
            bus (str): Unique identifier of the bus.
            waveform (Waveform | IQPair): A single waveform or an I/Q pair of waveforms
        """

    @overload
    def play(
        self,
        bus: str,
        waveform: str,
    ) -> None:
        """Play a named waveform on the bus.

        Args:
            bus (str): Unique identifier of the bus.
            waveform (str): An identifier of a named waveform.
        """

    def play(
        self,
        bus: str,
        waveform: Waveform | IQPair | str,
    ) -> None:
        """Play a waveform, IQPair, or calibrated operation on the specified bus.

        This method handles both playing a waveform or IQPair, and playing a
        calibrated operation based on the type of the argument provided.

        Args:
            bus (str): Unique identifier of the bus.
            waveform (Waveform | IQPair | str): The waveform, IQPair, or alias of named waveform to play.
        """
        operation = (
            PlayWithCalibratedWaveform(bus=bus, waveform=waveform)
            if isinstance(waveform, str)
            else Play(bus=bus, waveform=waveform)
        )
        self._active_block.append(operation)
        self._buses.add(bus)

    @requires_domain("duration", Domain.Time)
    def wait(self, bus: str, duration: int):
        """Adds a delay on the bus with a specified time.

        Args:
            bus (str): Unique identifier of the bus.
            time (int): Duration of the delay.
        """
        operation = Wait(bus=bus, duration=duration)
        self._active_block.append(operation)
        self._buses.add(bus)

    @requires_domain("duration", Domain.Time)
    def wait_trigger(self, bus: str, duration: int, port: int | None = None):
        """Adds a delay on the bus and wait for an trigger signal to arrive.

        Args:
            bus (str): Unique identifier of the bus.
            duration (int): Duration of the delay after the trigger is received. Minimum of 4 ns.
            port (optional, int | None): Port channel of the trigger input. Defaults to None.
        """
        operation = WaitTrigger(bus=bus, duration=duration, port=port)
        self._active_block.append(operation)
        self._buses.add(bus)

    @overload
    def measure(self, bus: str, waveform: IQPair, weights: IQPair, save_adc: bool = False):
        """Play a pulse and acquire results.

        Args:
            bus (str): Unique identifier of the bus.
            waveform (IQPair): Waveform played during measurement.
            weights (IQPair): Weights used during demodulation/integration.
            save_adc (bool, optional): If ADC data should be saved. Defaults to False.
        """

    @overload
    def measure(self, bus: str, waveform: str, weights: IQPair, save_adc: bool = False):
        """Play a named pulse and acquire results.

        Args:
            bus (str): Unique identifier of the bus.
            waveform (str): Waveform played during measurement.
            weights (IQPair): Weights used during demodulation/integration.
            save_adc (bool, optional): If ADC data should be saved. Defaults to False.
        """

    @overload
    def measure(self, bus: str, waveform: IQPair, weights: str, save_adc: bool = False):
        """Play a named pulse and acquire results.

        Args:
            bus (str): Unique identifier of the bus.
            waveform (IQPair): Waveform played during measurement.
            weights (str): Weights used during demodulation/integration.
            save_adc (bool, optional): If ADC data should be saved. Defaults to False.
        """

    @overload
    def measure(self, bus: str, waveform: str, weights: str, save_adc: bool = False):
        """Play a named pulse and acquire results.

        Args:
            bus (str): Unique identifier of the bus.
            waveform (str): Waveform played during measurement.
            weights (str): Weights used during demodulation/integration.
            save_adc (bool, optional): If ADC data should be saved. Defaults to False.
        """

    def measure(self, bus: str, waveform: IQPair | str, weights: IQPair | str, save_adc: bool = False):
        """Play a pulse and acquire results.

        Args:
            bus (str): Unique identifier of the bus.
            waveform (IQPair): Waveform played during measurement.
            weights (IQPair): Weights used during demodulation/integration.
            save_adc (bool, optional): If ADC data should be saved. Defaults to False.
        """
        operation: (
            Measure
            | MeasureWithCalibratedWaveform
            | MeasureWithCalibratedWeights
            | MeasureWithCalibratedWaveformWeights
        )
        if isinstance(waveform, IQPair) and isinstance(weights, IQPair):
            operation = Measure(bus=bus, waveform=waveform, weights=weights, save_adc=save_adc)
        elif isinstance(waveform, str) and isinstance(weights, IQPair):
            operation = MeasureWithCalibratedWaveform(bus=bus, waveform=waveform, weights=weights, save_adc=save_adc)
        elif isinstance(waveform, IQPair) and isinstance(weights, str):
            operation = MeasureWithCalibratedWeights(bus=bus, waveform=waveform, weights=weights, save_adc=save_adc)
        elif isinstance(waveform, str) and isinstance(weights, str):
            operation = MeasureWithCalibratedWaveformWeights(
                bus=bus, waveform=waveform, weights=weights, save_adc=save_adc
            )
        self._active_block.append(operation)
        self._buses.add(bus)

    def sync(self, buses: list[str] | None = None):
        """Synchronize operations between buses, so the operations following will start at the same time.

        If no buses are given, then the synchronization will involve all buses present in the QProgram.

        Args:
            buses (list[str], optional): List of unique identifiers of the buses. Defaults to None.
        """
        operation = Sync(buses=buses)
        self._active_block.append(operation)
        if buses:
            self._buses.update(buses)

    def reset_phase(self, bus: str):
        """Reset the absolute phase of the NCO associated with the bus.

        Args:
            bus (str): Unique identifier of the bus.
        """
        operation = ResetPhase(bus=bus)
        self._active_block.append(operation)
        self._buses.add(bus)

    @requires_domain("phase", Domain.Phase)
    def set_phase(self, bus: str, phase: float):
        """Set the absolute phase of the NCO associated with the bus.

        Args:
            bus (str): Unique identifier of the bus.
            phase (float): The new absolute phase of the NCO.
        """
        operation = SetPhase(bus=bus, phase=phase)
        self._active_block.append(operation)
        self._buses.add(bus)

    @requires_domain("frequency", Domain.Frequency)
    def set_frequency(self, bus: str, frequency: float):
        """Set the frequency of the NCO associated with bus.

        Args:
            bus (str): Unique identifier of the bus.
            frequency (float): The new frequency of the NCO.
        """
        operation = SetFrequency(bus=bus, frequency=frequency)
        self._active_block.append(operation)
        self._buses.add(bus)

    @requires_domain("gain", Domain.Voltage)
    def set_gain(self, bus: str, gain: float):
        """Set the gain of the AWG associated with bus.

        Args:
            bus (str): Unique identifier of the bus.
            gain (float): The new gain of the AWG.
        """
        operation = SetGain(bus=bus, gain=gain)
        self._active_block.append(operation)
        self._buses.add(bus)

    @requires_domain("offset_path0", Domain.Voltage)
    @requires_domain("offset_path1", Domain.Voltage)
    def set_offset(self, bus: str, offset_path0: float, offset_path1: float | None = None):
        """Set the gain of the AWG associated with bus.

        Args:
            bus (str): Unique identifier of the bus.
            offset_path0 (float): The new offset of the AWG for path0.
            offset_path1 (float): The new offset of the AWG for path1.
        """
        operation = SetOffset(bus=bus, offset_path0=offset_path0, offset_path1=offset_path1)
        self._active_block.append(operation)
        self._buses.add(bus)

    @requires_domain("duration", Domain.Time)
    def set_trigger(self, bus: str, duration: int, outputs: list[int] | int | None = None, position: str = "start"):
        """Set the trigger output for a given instrument.
        Args:
            bus (str): Unique identifier of the bus.
            duration (int): Duration of the trigger pulse. Minimum of 4 ns.
            outputs(optional, list[int] | int | None): Port channel/s of the trigger output. Defaults to None.
            outputs(optional, str): Trigger position in respective to the pulse location, it can be either `start` or `end. Defaults to start.
        """
        operation = SetTrigger(bus=bus, outputs=outputs, duration=duration, position=position)
        self._active_block.append(operation)
        self._buses.add(bus)

    @yaml.register_class
    class _QbloxInterface:
        def __init__(self, qprogram: "QProgram"):
            self.qprogram = qprogram
            self.disable_autosync: bool = False
            self.latch_enabled: list[str] = []
            self.trigger_network_required: dict[str, int] = {}

        @overload
        def acquire(self, bus: str, weights: IQPair, save_adc: bool = False):
            """Acquire results based on the given weights.

            Args:
                bus (str): Unique identifier of the bus.
                weights (IQPair): Weights used during acquisition.
            """

        @overload
        def acquire(self, bus: str, weights: str, save_adc: bool = False):
            """Acquire results based on the given weights.

            Args:
                bus (str): Unique identifier of the bus.
                weights (str): Weights used during acquisition.
            """

        def acquire(self, bus: str, weights: IQPair | str, save_adc: bool = False):
            """Acquire results based on the given weights.

            Args:
                bus (str): Unique identifier of the bus.
                weights (IQPair | str): Weights used during acquisition.
            """
            operation = (
                Acquire(bus=bus, weights=weights, save_adc=save_adc)
                if isinstance(weights, IQPair)
                else AcquireWithCalibratedWeights(bus=bus, weights=weights, save_adc=save_adc)
            )
            self.qprogram._active_block.append(operation)
            self.qprogram._buses.add(bus)

        @overload
        def play(self, bus: str, waveform: Waveform | IQPair, wait_time: int) -> None:
            """Play a single waveform or an I/Q pair of waveforms on the bus.

            Args:
                bus (str): Unique identifier of the bus.
                waveform (Waveform | IQPair): A single waveform or an I/Q pair of waveforms
            """

        @overload
        def play(self, bus: str, waveform: str, wait_time: int) -> None:
            """Play a named waveform on the bus.

            Args:
                bus (str): Unique identifier of the bus.
                waveform (str): An identifier of a named waveform.
            """

        def play(self, bus: str, waveform: Waveform | IQPair | str, wait_time: int) -> None:
            """Play a waveform, IQPair, or calibrated operation on the specified bus.

            This method handles both playing a waveform or IQPair, and playing a
            calibrated operation based on the type of the argument provided.

            Args:
                bus (str): Unique identifier of the bus.
                waveform (Waveform | IQPair | str): The waveform, IQPair, or alias of named waveform to play.
                wait_time (int): Overwrite the value of Q1ASM play instruction's wait_time parameter.
            """
            operation = (
                PlayWithCalibratedWaveform(bus=bus, waveform=waveform, wait_time=wait_time)
                if isinstance(waveform, str)
                else Play(bus=bus, waveform=waveform, wait_time=wait_time)
            )
            self.qprogram._active_block.append(operation)
            self.qprogram._buses.add(bus)

        def measure_reset(
            self,
            bus: str,
            waveform: IQPair,
            weights: IQPair,
            control_bus: str,
            reset_pulse: IQPair,
            trigger_address: int = 1,
            save_adc: bool = False,
        ):
            """Play a measurement and conditionally apply a reset pulse based on the result. This enables active reset for transmon qubits.

            If the thresholded measurement result is 1, a corrective pulse is applied on the control_bus.
            If the result is 0, the control_bus waits instead.

            Args:
                bus (str): Identifier of the measurement bus.
                waveform (IQPair): Waveform played during measurement.
                weights (IQPair): Weights used for demodulation/integration.
                control_bus (str): Identifier of the control/reset bus.
                reset_pulse (IQPair): Pulse used for active reset.
                trigger_address (int, optional): Trigger address for synchronization. Defaults to 1.
                save_adc (bool, optional): Whether to save ADC data. Defaults to False.
            """

            operation = MeasureReset(
                bus=bus,
                waveform=waveform,
                weights=weights,
                control_bus=control_bus,
                reset_pulse=reset_pulse,
                trigger_address=trigger_address,
                save_adc=save_adc,
            )
            self.qprogram._active_block.append(operation)
            self.qprogram._buses.add(bus)
            self.qprogram._buses.add(control_bus)
            self.latch_enabled.append(control_bus)
            self.trigger_network_required[bus] = trigger_address

        def set_markers(self, bus: str, mask: str):
            """Set the markers based on a 4-bit binary mask.

            Args:
                bus (str): Unique identifier of the bus.
                mask (str): A 4-bit mask, where 0 means that the associated marker is open (no signal), and 1 means that the marker is closed (signal).
            """
            operation = SetMarkers(bus=bus, mask=mask)
            self.qprogram._active_block.append(operation)
            self.qprogram._buses.add(bus)

    @yaml.register_class
    class _QuantumMachinesInterface:
        def __init__(self, qprogram: "QProgram"):
            self.qprogram = qprogram

        @overload
        def measure(
            self,
            bus: str,
            waveform: IQPair,
            weights: IQPair,
            save_adc: bool = False,
            rotation: float = 0.0,
            demodulation: bool = True,
        ):
            """Play a pulse and acquire results.

            Args:
                bus (str): Unique identifier of the bus.
                waveform (IQPair): Waveform played during measurement.
                weights (IQPair): Weights used during demodulation/integration.
                save_adc (bool, optional): If ADC data should be saved. Defaults to False.
                rotation (float, optional): Angle in radians to rotate the IQ plane during demodulation/integration. Defaults to 0.0
                demodulation (bool, optional): If demodulation is enabled. Defaults to True.
            """

        @overload
        def measure(
            self,
            bus: str,
            waveform: str,
            weights: IQPair,
            save_adc: bool = False,
            rotation: float = 0.0,
            demodulation: bool = True,
        ):
            """Play a named pulse and acquire results.

            Args:
                bus (str): Unique identifier of the bus.
                waveform (str): Waveform played during measurement.
                weights (IQPair): Weights used during demodulation/integration.
                save_adc (bool, optional): If ADC data should be saved. Defaults to False.
                rotation (float, optional): Angle in radians to rotate the IQ plane during demodulation/integration. Defaults to 0.0
                demodulation (bool, optional): If demodulation is enabled. Defaults to True.
            """

        @overload
        def measure(
            self,
            bus: str,
            waveform: IQPair,
            weights: str,
            save_adc: bool = False,
            rotation: float = 0.0,
            demodulation: bool = True,
        ):
            """Play a named pulse and acquire results.

            Args:
                bus (str): Unique identifier of the bus.
                waveform (IQPair): Waveform played during measurement.
                weights (str): Weights used during demodulation/integration.
                save_adc (bool, optional): If ADC data should be saved. Defaults to False.
                rotation (float, optional): Angle in radians to rotate the IQ plane during demodulation/integration. Defaults to 0.0
                demodulation (bool, optional): If demodulation is enabled. Defaults to True.
            """

        @overload
        def measure(
            self,
            bus: str,
            waveform: str,
            weights: str,
            save_adc: bool = False,
            rotation: float = 0.0,
            demodulation: bool = True,
        ):
            """Play a named pulse and acquire results.

            Args:
                bus (str): Unique identifier of the bus.
                waveform (str): Waveform played during measurement.
                weights (str): Weights used during demodulation/integration.
                save_adc (bool, optional): If ADC data should be saved. Defaults to False.
                rotation (float, optional): Angle in radians to rotate the IQ plane during demodulation/integration. Defaults to 0.0
                demodulation (bool, optional): If demodulation is enabled. Defaults to True.
            """

        def measure(
            self,
            bus: str,
            waveform: IQPair | str,
            weights: IQPair | str,
            save_adc: bool = False,
            rotation: float = 0.0,
            demodulation: bool = True,
        ):
            """Play a pulse and acquire results.

            Args:
                bus (str): Unique identifier of the bus.
                waveform (IQPair): Waveform played during measurement.
                weights (IQPair): Weights used during demodulation/integration.
                save_adc (bool, optional): If raw ADC data should be saved. Defaults to False.
                rotation (float, optional): Angle in radians to rotate the IQ plane during demodulation/integration. Defaults to 0.0
                demodulation (bool, optional): If demodulation is enabled. Defaults to True.
            """
            operation: (
                Measure
                | MeasureWithCalibratedWaveform
                | MeasureWithCalibratedWeights
                | MeasureWithCalibratedWaveformWeights
            )
            if isinstance(waveform, IQPair) and isinstance(weights, IQPair):
                operation = Measure(
                    bus=bus,
                    waveform=waveform,
                    weights=weights,
                    save_adc=save_adc,
                    rotation=rotation,
                    demodulation=demodulation,
                )
            elif isinstance(waveform, str) and isinstance(weights, IQPair):
                operation = MeasureWithCalibratedWaveform(
                    bus=bus,
                    waveform=waveform,
                    weights=weights,
                    save_adc=save_adc,
                    rotation=rotation,
                    demodulation=demodulation,
                )
            elif isinstance(waveform, IQPair) and isinstance(weights, str):
                operation = MeasureWithCalibratedWeights(
                    bus=bus,
                    waveform=waveform,
                    weights=weights,
                    save_adc=save_adc,
                    rotation=rotation,
                    demodulation=demodulation,
                )
            elif isinstance(waveform, str) and isinstance(weights, str):
                operation = MeasureWithCalibratedWaveformWeights(
                    bus=bus,
                    waveform=waveform,
                    weights=weights,
                    save_adc=save_adc,
                    rotation=rotation,
                    demodulation=demodulation,
                )
            self.qprogram._active_block.append(operation)
            self.qprogram._buses.add(bus)

    @yaml.register_class
    class _QdacInterface:
        def __init__(self, qprogram: "QProgram"):
            self.qprogram = qprogram

        @overload
        def play(
            self,
            bus: str,
            waveform: Waveform | IQPair,
            dwell: int | None = None,
            delay: int | None = None,
            repetitions: int | None = None,
        ) -> None:
            """Play a single waveform or an I/Q pair of waveforms on the bus.

            Args:
                bus (str): Unique identifier of the bus.
                waveform (Waveform | IQPair): A single waveform or an I/Q pair of waveforms
                dwell (int | None, optional): Resolution un us of the QDACII pulse with a minimum of 2 us. Defaults to 2 inside QDACII compiler.
                delay (int | None, optional): Delay of the QDACII pulse. Defaults to 0 inside QDACII compiler.
                repetitions (int | None, optional): Number of pulse repetitions. Defaults to the default repetitions inside QDACII compiler.
            """

        @overload
        def play(
            self,
            bus: str,
            waveform: str,
            dwell: int | None = None,
            delay: int | None = None,
            repetitions: int | None = None,
        ) -> None:
            """Play a named waveform on the bus.

            Args:
                bus (str): Unique identifier of the bus.
                waveform (str): An identifier of a named waveform.
                dwell (int | None, optional): Resolution un us of the QDACII pulse with a minimum of 2 us. Defaults to 2 inside QDACII compiler.
                delay (int | None, optional): Delay of the QDACII pulse. Defaults to 0 inside QDACII compiler.
                repetitions (int | None, optional): Number of pulse repetitions. Defaults to the default repetitions inside QDACII compiler.
            """

        def play(
            self,
            bus: str,
            waveform: Waveform | IQPair | str,
            dwell: int | None = None,
            delay: int | None = None,
            repetitions: int | None = None,
        ) -> None:
            """Play a waveform, IQPair, or calibrated operation on the specified bus.

            This method handles both playing a waveform or IQPair, and playing a
            calibrated operation based on the type of the argument provided.

            Args:
                bus (str): Unique identifier of the bus.
                waveform (Waveform | IQPair | str): The waveform, IQPair, or alias of named waveform to play.
                dwell (int | None, optional): Resolution un us of the QDACII pulse with a minimum of 2 us. Defaults to 2 inside QDACII compiler.
                delay (int | None, optional): Delay of the QDACII pulse. Defaults to 0 inside QDACII compiler.
                repetitions (int | None, optional): Number of pulse repetitions. Defaults to the default repetitions inside QDACII compiler.
            """

            operation = (
                PlayWithCalibratedWaveform(
                    bus=bus, waveform=waveform, dwell=dwell, delay=delay, repetitions=repetitions
                )
                if isinstance(waveform, str)
                else Play(bus=bus, waveform=waveform, dwell=dwell, delay=delay, repetitions=repetitions)
            )
            self.qprogram._active_block.append(operation)
            self.qprogram._buses.add(bus)

    def draw(
        self,
        time_window: int | None = None,
        averages_displayed: bool = False,
        acquisition_showing: bool = True,
        calibration: Calibration | None = None,
    ):
        """Draw the QProgram using QBlox Compiler

        Args:
            time_window (int): Allows the user to stop the plotting after the specified number of ns have been plotted. The plotting might not be the precise number of ns inputted.
                For example, if the timeout is 100 ns but there is a play operation of 150 ns, the plot will display the data until 150 ns. Defaults to None.
            averages_displayed (bool): False means that all loops on the sequencer starting with avg will only loop once, and True shows all iterations. Defaults to False.
            acquisition_showing (bool): Allows visualing the acquisition period on the plot. Defaults to True.

        Returns:
            plotly object: plotly.graph_objs._figure.Figure
        """

        from qililab.instruments.qblox.qblox_draw import QbloxDraw
        from qililab.qprogram.qblox_compiler import QbloxCompiler

        qblox_draw = QbloxDraw()
        compiler = QbloxCompiler()
        sequencer = compiler.compile(qprogram=self, calibration=calibration)
        plotly_figure, _ = qblox_draw.draw(
            sequencer=sequencer,
            time_window=time_window,
            averages_displayed=averages_displayed,
            acquisition_showing=acquisition_showing,
        )
        return plotly_figure
