@startuml

participant Platform as plat
participant Schema as schema
participant Instruments as instrs
participant Chip as chip

[-> plat ++: get_element (alias, category, id)
alt element is a platform
        note right of plat: result = self.settings
else
        plat -> schema ++: get_instrument (alias, category, id)
        schema -> instrs ++: get_instrument (alias, category, id)
        alt alias is not None
                note right of instrs: result = first element in list of elements with alias = alias
        else
                note right of instrs: result = first element in list of elements with id = id and category = category
        end
        return
        return
        opt element is None
                opt category is not None AND id is not None
                        plat -> schema ++: get_node_from_id (id)
                        schema -> chip ++: get_node_from_id (id)
                        note right of chip: result = first element in list of nodes with id = id
                        return result
                        return result
                end
                opt alias is not None
                        plat -> schema ++: get_node_from_alias (alias)
                        schema -> chip ++: get_node_from_alias (alias)
                        note right of chip: result = first element in list of nodes with alias = alias
                        return result
                        return result
                end
        end
end
return result

@enduml
