@startuml

participant Execution as exe
participant Platform as plat
participant Schema as schema
participant InstrumentControllers as instrcontrollers
participant InstrumentController as instrcontroller
participant InstrumentControllerSettings as instrcontrollerset
participant Connection as conn
participant Instrument as instr
participant BusesExecution as busesexe
participant BusExecution as busexe
participant Bus as bus
participant BusSettings as busset
participant SystemControl as system_control
participant Attenuator as attenuator
participant MiniCircuitsDriver as minicircuits


[-> exe ++: __enter__()
exe -> exe: connect ()
activate exe #7F1CDB
exe -> plat ++: connect ()
plat -> schema ++: connect ()
schema -> instrcontrollers ++: connect ()
loop instrument_controller in elements
    instrcontrollers -> instrcontroller ++: connect ()
    instrcontroller -> instrcontroller: initialize_device_and_set_to_all_modules ()
    activate instrcontroller #7F1CDB
    instrcontroller -> instrcontroller: initialize_device ()
    activate instrcontroller #E6033F
    note right of instrcontroller #E68AA3: InstrumentController \ninitialize device
    return
    instrcontroller -> instrcontroller: set_device_to_all_modules ()
    activate instrcontroller #E6033F
    note right of instrcontroller #E68AA3: InstrumentController \nset device to all modules
    return
    instrcontroller -> instrcontrollerset ++: connect_connection (device, device_name)
    instrcontrollerset -> conn ++: connect (device, device_name)
    return
    return
    instrcontroller -> instrcontrollerset ++: get_settings_reset ()
    return settings_reset
    opt settings_reset
        instrcontroller -> instrcontroller: reset ()
        activate instrcontroller #E6033F
        loop module in modules
            instrcontroller -> instr ++: reset ()
            note right of instr #E68AA3: Instrument reset
            return
        end
    end
    return
    instrcontroller -> instrcontroller: initial_setup ()
    activate instrcontroller #E6033F
    loop module in modules
        instrcontroller -> instr ++: initial_setup ()
        note right of instr #E68AA3: Instrument initial setup
        return
    end
    return
end
return
return
return 
return
return
return

exe -> exe: setup ()
activate exe #7F1CDB
exe -> busesexe ++: setup ()
loop bus in buses
    busesexe -> busexe ++: setup ()
    busexe -> bus ++: get_target_frequencies ()
    return target_frequencies
    busexe -> bus ++: setup_system_control (target_frequencies)
    bus -> busset ++: setup_system_control (target_frequencies)
    busset -> system_control ++: setup (target_frequencies)
    note right of system_control #E68AA3: SystemControl setup
    return
    return
    return
    opt self.attenuator is not None
        busexe -> bus ++: setup_attenuator ()
        bus -> busset ++: setup_attenuator ()
        busset -> attenuator ++: setup ()
        attenuator -> minicircuits ++: setup (attenuation)
        minicircuits -> minicircuits: http_request (SETATT = attenuation)
        activate minicircuits #7F1CDB
        return
        return
        return
        return
        return
    end
return
end
return
return

exe -> exe: start()
activate exe #7F1CDB
exe -> busesexe ++: start ()
loop bus in buses
    busesexe -> busexe ++: start ()
    busexe -> bus ++: start_system_control ()
    bus -> busset ++: start_system_control ()
    busset -> system_control ++: start ()
    note right of system_control #E68AA3: SystemControl start
    return
    return
    return
    return
end
return
return
[<-- exe

@enduml