# Copyright 2023 Qilimanjaro Quantum Tech
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""File containing the supported native gates."""

from typing import ClassVar

import numpy as np
from qilisdk.core import Parameter
from qilisdk.digital.gates import BasicGate
from qilisdk.yaml import yaml


@yaml.register_class
class Rmw(BasicGate):
    r"""Microwave rotation in the equatorial plane (native single-qubit pulse).

    This gate represents a resonant microwave (e.g., DRAG-shaped) pulse implementing a rotation by
    angle ``theta`` around an axis in the XY plane defined by the drive phase ``phase``.

    Mathematically, it can be written as a Z-X-Z decomposition
    .. math::

        R_{MW}(\theta, \phi) = Z_{\phi}\, X_{\theta}\, Z_{-\phi},

    which is equivalent to a rotation generated by :math:`\cos\phi\,\sigma_x + \sin\phi\,\sigma_y`:
    .. math::

        R_{MW}(\theta,\phi)
        = \exp\!\left(-\frac{i\theta}{2}\left(\cos\phi\,\sigma_x + \sin\phi\,\sigma_y\right)\right)
        =
        \begin{pmatrix}
            \cos(\tfrac{\theta}{2}) & -i e^{-i\phi}\sin(\tfrac{\theta}{2}) \\
            -i e^{i\phi}\sin(\tfrac{\theta}{2}) & \cos(\tfrac{\theta}{2})
        \end{pmatrix}.

    Implementation note (hardware-aware):
    In pulse-level execution, :math:`Z` rotations are virtual frame updates. The trailing
    :math:`Z_{\phi}` can be absorbed into subsequent operations, so a common realization is a single
    Virtual-Z by :math:`-\phi` followed by a microwave pulse of area :math:`\theta` with drive phase
    :math:`\phi`.

    Together with Virtual-Z gates, any single-qubit unitary can be expressed as
    .. math::

        U(\theta,\phi,\lambda) = Z_\phi X_\theta Z_\lambda
        = R_{MW}(\theta,\phi)\, Z_{\lambda+\phi}
        = Z_{\phi+\lambda}\, R_{MW}(\theta,-\lambda).

    Args:
        qubit (int): Target qubit index.
        theta (float): Rotation angle in radians.
        phase (float): Microwave drive phase in radians (sets the rotation axis in the XY plane).
    """

    PARAMETER_NAMES: ClassVar[list[str]] = ["theta", "phase"]

    def __init__(self, qubit: int, *, theta: float, phase: float):
        super().__init__(
            target_qubits=(qubit,),
            parameters={
                "theta": theta if isinstance(theta, Parameter) else Parameter("theta", theta),
                "phase": phase if isinstance(phase, Parameter) else Parameter("phase", phase),
            },
        )

    @property
    def name(self) -> str:
        return "Rmw"

    @property
    def theta(self) -> float:
        return self.get_parameters()["theta"]

    @property
    def phase(self) -> float:
        return self.get_parameters()["phase"]

    def _generate_matrix(self) -> np.ndarray:
        theta = float(self.theta)
        phi = float(self.phase)

        cos = np.cos(theta / 2)
        sin = np.sin(theta / 2)

        return np.array(
            [
                [cos, -1j * np.exp(-1j * phi) * sin],
                [-1j * np.exp(1j * phi) * sin, cos],
            ],
            dtype=complex,
        )
