@startuml

participant Platform as plat
participant PlatformSettings as platset
participant DDBBElement as DDBB
participant GateSettings as gateset
participant Instrument as instr
participant Node as node

[-> plat ++: set_parameter (alias, category, id, parameter, value)
alt (alias is not None AND alias is a platform alias) OR (category is not None AND category is a platform category)
        alt alias == Category.Platform.value
                plat -> platset ++: set_parameter (parameter, value)
                platset -> DDBB ++: set_parameter (parameter, value)
                note right of DDBB: setattr (self, parameter, value)
                return
                return
        else
                plat -> platset ++: set_parameter (parameter, value, alias)
                platset -> platset: get_gate (alias)
                activate platset #7F1CDB
                note right of platset: result = first gate with name = alias in gates
                return result
                note right of platset: settings = result
                opt not hasattr (settings, parameter)
                        platset -> gateset ++: get_shape ()
                        return shape
                        note right of platset: settings = shape
                end
                note right of platset: setattr (settings, parameter, value)
                return
        end
else
        plat -> plat: get_element (alias, category, id)
        activate plat #7F1CDB
        note right of plat #C2A5DC: Platform get_element
        return result
        note right of plat: element = result
        alt element is a PlatformSettings
                plat -> platset ++: set_parameter (parameter, value)
                return
        else element is an Instrument
                plat -> instr ++: set_parameter (parameter, value)
                return
        else element is a Node
                plat -> node ++: set_parameter (parameter, value)
                return
        end
end
return