id: 0
name: qili_schema  # unique name
category: schema  # general name
buses:
  bus_0:
    qubit_control:
      name: qcm
      id: 0
    signal_generator:
      name: rohde_schwarz
      id: 0
    resonator:
      name: resonator
      id: 0
  bus_1:
    qubit_control:
      name: qrm
      id: 0
    signal_generator:
      name: rohde_schwarz
      id: 1
    resonator:
      name: resonator
      id: 0
