id_: 0
name: qili_schema  # unique name
category: schema  # general name
buses:
  - - category: qubit_control
      name: qblox_qcm
      id_: 0
    - category: signal_generator
      name: rohde_schwarz
      id_: 0
    - category: mixer
      name: mixer
      id_: 0
    - category: resonator
      name: resonator
      id_: 0
  - - category: qubit_readout  # connection QRM -> Resonator
      name: qblox_qrm
      id_: 0
    - category: signal_generator
      name: rohde_schwarz
      id_: 1
    - category: resonator
      name: resonator
      id_: 0
    - category: mixer  # up-conversion mixer
      name: mixer
      id_: 1
  - - category: qubit_readout  # connection Resonator -> QRM
      name: qblox_qrm
      id_: 0
    - category: signal_generator
      name: rohde_schwarz
      id_: 1
    - category: resonator
      name: resonator
      id_: 0
    - category: mixer  # down-conversion mixer
      name: mixer
      id_: 2
