id_: 0
name: qili_schema  # unique name
category: schema  # general name
buses:
  - - category: qubit_control
      name: qcm
      id_: 0
    - category: signal_generator
      name: rohde_schwarz
      id_: 0
    - category: resonator
      name: resonator
      id_: 0
  - - category: qubit_readout
      name: qrm
      id_: 0
    - category: signal_generator
      name: rohde_schwarz
      id_: 1
    - category: resonator
      name: resonator
      id_: 0
