buses:
  elements:
    - readout: false
      qubit_instrument:
        id_: 0
        name: qblox_qcm  # unique name
        category: qubit_instrument  # general name
        ip: 192.168.0.3
        firmware: 0.7.0
        reference_clock: internal
        sequencer: 0
        sync_enabled: true
        gain: 1
      signal_generator:
        id_: 0
        name: rohde_schwarz  # unique name
        category: signal_generator  # general name
        ip: 192.168.0.10
        firmware: 4.30.046.295
        frequency: 3644000000.0
        power: 15
      mixer_up:
        id_: 0
        name: mixer_up  # unique name
        category: mixer  # general name
        epsilon: 0
        delta: 0
        offset_i: 0
        offset_q: 0
        up_conversion: true
      qubit:
        id_: 0
        name: qubit
        category: qubit
        pi_pulse_amplitude: 1
        pi_pulse_duration: 100
        pi_pulse_frequency: 100000000.0
        qubit_frequency: 3544000000.0
        min_voltage: 950
        max_voltage: 1775
    - readout: true
      qubit_instrument:
        id_: 1
        name: qblox_qrm  # unique name
        category: qubit_instrument  # general name
        ip: 192.168.0.4
        firmware: 0.7.0
        reference_clock: external
        sequencer: 0
        sync_enabled: true
        gain: 0.5
        acquire_trigger_mode: sequencer
        hardware_average_enabled: true
        start_integrate: 130
        sampling_rate: 1000000000
        integration_length: 2000
        integration_mode: ssb
        sequence_timeout: 1
        acquisition_timeout: 1
        acquisition_name: "single"
        delay_before_readout: 50
      signal_generator:
        id_: 1
        name: rohde_schwarz  # unique name
        category: signal_generator  # general name
        ip: 192.168.0.7
        firmware: 4.30.046.295
        frequency: 7307720000.0
        power: 15
      mixer_up:
        id_: 1
        name: mixer_up  # unique name
        category: mixer  # general name
        epsilon: 0
        delta: 0
        offset_i: 0
        offset_q: 0
        up_conversion: true
      resonator:
        id_: 0
        name: resonator
        category: resonator
        qubits:  # list of qubit settings
          - id_: 0
            name: qubit
            category: qubit
            pi_pulse_amplitude: 1
            pi_pulse_duration: 100
            pi_pulse_frequency: 100000000.0
            qubit_frequency: 3544000000.0
            min_voltage: 950
            max_voltage: 1775
      mixer_down:
        id_: 2
        name: mixer_down  # unique name
        category: mixer  # general name
        epsilon: 0
        delta: 0
        offset_i: 0
        offset_q: 0
        up_conversion: false
    - readout: false
      qubit_instrument:
        id_: 0
        name: qblox_qcm  # unique name
        category: qubit_instrument  # general name
        ip: 192.168.0.3
        firmware: 0.7.0
        reference_clock: internal
        sequencer: 0
        sync_enabled: true
        gain: 1
      signal_generator:
        id_: 0
        name: rohde_schwarz  # unique name
        category: signal_generator  # general name
        ip: 192.168.0.10
        firmware: 4.30.046.295
        frequency: 3644000000.0
        power: 15
      mixer_up:
        id_: 0
        name: mixer_up  # unique name
        category: mixer  # general name
        epsilon: 0
        delta: 0
        offset_i: 0
        offset_q: 0
        up_conversion: true
      qubit:
        id_: 1
        name: qubit
        category: qubit
        pi_pulse_amplitude: 1
        pi_pulse_duration: 100
        pi_pulse_frequency: 100000000.0
        qubit_frequency: 3544000000.0
        min_voltage: 950
        max_voltage: 1775
    - readout: true
      qubit_instrument:
        id_: 1
        name: qblox_qrm  # unique name
        category: qubit_instrument  # general name
        ip: 192.168.0.4
        firmware: 0.7.0
        reference_clock: external
        sequencer: 0
        sync_enabled: true
        gain: 0.5
        acquire_trigger_mode: sequencer
        hardware_average_enabled: true
        start_integrate: 130
        sampling_rate: 1000000000
        integration_length: 2000
        integration_mode: ssb
        sequence_timeout: 1
        acquisition_timeout: 1
        acquisition_name: "single"
        delay_before_readout: 50
      signal_generator:
        id_: 1
        name: rohde_schwarz  # unique name
        category: signal_generator  # general name
        ip: 192.168.0.7
        firmware: 4.30.046.295
        frequency: 7307720000.0
        power: 15
      mixer_up:
        id_: 1
        name: mixer_up  # unique name
        category: mixer  # general name
        epsilon: 0
        delta: 0
        offset_i: 0
        offset_q: 0
        up_conversion: true
      resonator:
        id_: 0
        name: resonator
        category: resonator
        qubits:  # list of qubit settings
          - id_: 1
            name: qubit
            category: qubit
            pi_pulse_amplitude: 1
            pi_pulse_duration: 100
            pi_pulse_frequency: 100000000.0
            qubit_frequency: 3544000000.0
            min_voltage: 950
            max_voltage: 1775
      mixer_down:
        id_: 2
        name: mixer_down  # unique name
        category: mixer  # general name
        epsilon: 0
        delta: 0
        offset_i: 0
        offset_q: 0
        up_conversion: false
