@startuml

participant QBloxModule as qblox
participant Pulsar_or_QcmQrm as dev

[-> qblox ++: reset ()
qblox -> qblox: clear_cache ()
activate qblox #7F1CDB
note right of qblox: cache = None
return
qblox -> dev ++: reset ()
return 
return

@enduml