on:
  pull_request:
    types: [ready_for_review]

name: Changelog Reminder

jobs:
  remind:
    name: Changelog Reminder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Changelog Reminder
        uses: peterjgrainger/action-changelog-reminder@v1.3.0
        with:
          changelog_regex: "changelog-dev.md"
          customPrMessage: |
            Hello. You may have forgotten to update the changelog!
            Please edit [`changelog-dev.md`](/qilimanjaro-tech/qililab/tree/main/doc/releases/changelog-dev.md) with:
            * A one-to-two sentence description of the change. You may include a small working example for new features.
            * A link back to this PR.
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
