name: CI build to PR

on:
  pull_request:
    branches:
      - main

jobs:
  code-review:
    runs-on: ubuntu-latest
    env:
      HOME_REPO: /home/repo

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: .github/workflows/pull_request_ci.yml

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r dev-requirements.txt

      - name: Code Quality
        run: |
          isort .
          black . --check
          flake8
          mypy
          interrogate -vv --fail-under=80
          bandit -r src

      - name: Install library
        run: |
          python -m pip install .

      - name: Test with pytest core
        run: |
          pytest --cov=./src --cov-report=xml

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
