name: Upload Python Package

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "0.27.2"
        required: true
        default: "0.27.2"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/qililab
    permissions:
      id-token: write 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.ref_name }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r dev-requirements.txt

      - name: Zip and build wheel
        run: |
          python -m pip install build wheel setuptools
          python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.2
