name: saruman
buses:
- alias: drive_bus
  instruments:
  - qcm-rf
  channels:
  - 0
  - 1
  - 2
  - 3
- alias: readout_bus
  instruments:
  - qrm-rf
  channels:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
instruments:
- type: qcm
  settings:
    alias: qcm
    channels:
    - id: 0
      outputs:
      - 0
      hardware_modulation: false
      intermediate_frequency:
      gain_imbalance: 0.0
      phase_imbalance: 0.0
      gain_i: 1.0
      gain_q: 0.0
      offset_i: 0.0
      offset_q: 0.0
    - id: 1
      outputs:
      - 1
      hardware_modulation: false
      intermediate_frequency:
      gain_imbalance: 0.0
      phase_imbalance: 0.0
      gain_i: 1.0
      gain_q: 0.0
      offset_i: 0.0
      offset_q: 0.0
    - id: 2
      outputs:
      - 2
      hardware_modulation: false
      intermediate_frequency:
      gain_imbalance: 0.0
      phase_imbalance: 0.0
      gain_i: 1.0
      gain_q: 0.0
      offset_i: 0.0
      offset_q: 0.0
    - id: 3
      outputs:
      - 3
      hardware_modulation: false
      intermediate_frequency:
      gain_imbalance: 0.0
      phase_imbalance: 0.0
      gain_i: 1.0
      gain_q: 0.0
      offset_i: 0.0
      offset_q: 0.0
    timeout: 1
    outputs:
    - port: 0
      offset: 0.0
    - port: 1
      offset: 0.0
    - port: 2
      offset: 0.0
    - port: 3
      offset: 0.0
- type: qrm
  settings:
    alias: qrm
    channels:
    - id: 0
      outputs:
      - 0
      hardware_modulation: true
      intermediate_frequency: 500000000.0
      gain_imbalance: 0.0
      phase_imbalance: 0.0
      gain_i: 1.0
      gain_q: 1.0
      offset_i: 0.0
      offset_q: 0.0
      inputs:
      - 0
      hardware_demodulation: true
      integration_length: 1000
      threshold: 0.0
      threshold_rotation: 0.0
      time_of_flight: 0
    - id: 1
      outputs:
      - 0
      hardware_modulation: true
      intermediate_frequency: 500000000.0
      gain_imbalance: 0.0
      phase_imbalance: 0.0
      gain_i: 1.0
      gain_q: 1.0
      offset_i: 0.0
      offset_q: 0.0
      inputs:
      - 0
      hardware_demodulation: true
      integration_length: 1000
      threshold: 0.0
      threshold_rotation: 0.0
      time_of_flight: 0
    - id: 2
      outputs:
      - 0
      hardware_modulation: true
      intermediate_frequency: 500000000.0
      gain_imbalance: 0.0
      phase_imbalance: 0.0
      gain_i: 1.0
      gain_q: 1.0
      offset_i: 0.0
      offset_q: 0.0
      inputs:
      - 0
      hardware_demodulation: true
      integration_length: 1000
      threshold: 0.0
      threshold_rotation: 0.0
      time_of_flight: 0
    - id: 3
      outputs:
      - 0
      hardware_modulation: true
      intermediate_frequency: 500000000.0
      gain_imbalance: 0.0
      phase_imbalance: 0.0
      gain_i: 1.0
      gain_q: 1.0
      offset_i: 0.0
      offset_q: 0.0
      inputs:
      - 0
      hardware_demodulation: true
      integration_length: 1000
      threshold: 0.0
      threshold_rotation: 0.0
      time_of_flight: 0
    - id: 4
      outputs:
      - 0
      hardware_modulation: true
      intermediate_frequency: 500000000.0
      gain_imbalance: 0.0
      phase_imbalance: 0.0
      gain_i: 1.0
      gain_q: 1.0
      offset_i: 0.0
      offset_q: 0.0
      inputs:
      - 0
      hardware_demodulation: true
      integration_length: 1000
      threshold: 0.0
      threshold_rotation: 0.0
      time_of_flight: 0
    - id: 5
      outputs:
      - 0
      hardware_modulation: true
      intermediate_frequency: 500000000.0
      gain_imbalance: 0.0
      phase_imbalance: 0.0
      gain_i: 1.0
      gain_q: 1.0
      offset_i: 0.0
      offset_q: 0.0
      inputs:
      - 0
      hardware_demodulation: true
      integration_length: 1000
      threshold: 0.0
      threshold_rotation: 0.0
      time_of_flight: 0
    timeout: 1
    outputs:
    - port: 0
      offset: 0.0
    - port: 1
      offset: 0.0
    inputs:
    - port: 0
      gain: 0
      offset: 0.0
    - port: 1
      gain: 0
      offset: 0.0
    scope_hardware_averaging: true
- type: qcm-rf
  settings:
    alias: qcm-rf
    channels:
    - id: 0
      outputs:
      - 0
      hardware_modulation: true
      intermediate_frequency: 500000000.0
      gain_imbalance: 0.0
      phase_imbalance: 0.0
      gain_i: 1.0
      gain_q: 1.0
      offset_i: 0.0
      offset_q: 0.0
    - id: 1
      outputs:
      - 0
      hardware_modulation: true
      intermediate_frequency: 500000000.0
      gain_imbalance: 0.0
      phase_imbalance: 0.0
      gain_i: 1.0
      gain_q: 1.0
      offset_i: 0.0
      offset_q: 0.0
    - id: 2
      outputs:
      - 0
      hardware_modulation: true
      intermediate_frequency: 500000000.0
      gain_imbalance: 0.0
      phase_imbalance: 0.0
      gain_i: 1.0
      gain_q: 1.0
      offset_i: 0.0
      offset_q: 0.0
    - id: 3
      outputs:
      - 0
      hardware_modulation: true
      intermediate_frequency: 500000000.0
      gain_imbalance: 0.0
      phase_imbalance: 0.0
      gain_i: 1.0
      gain_q: 1.0
      offset_i: 0.0
      offset_q: 0.0
    - id: 4
      outputs:
      - 0
      hardware_modulation: true
      intermediate_frequency: 500000000.0
      gain_imbalance: 0.0
      phase_imbalance: 0.0
      gain_i: 1.0
      gain_q: 1.0
      offset_i: 0.0
      offset_q: 0.0
    - id: 5
      outputs:
      - 0
      hardware_modulation: true
      intermediate_frequency: 500000000.0
      gain_imbalance: 0.0
      phase_imbalance: 0.0
      gain_i: 1.0
      gain_q: 1.0
      offset_i: 0.0
      offset_q: 0.0
    timeout: 1
    outputs:
    - port: 0
      lo_enabled: true
      lo_frequency: 10000000000.0
      attenuation: 0
      offset_i: 0.0
      offset_q: 0.0
    - port: 1
      lo_enabled: true
      lo_frequency: 10000000000.0
      attenuation: 0
      offset_i: 0.0
      offset_q: 0.0
- type: qrm-rf
  settings:
    alias: qrm-rf
    channels:
    - id: 0
      outputs:
      - 0
      hardware_modulation: true
      intermediate_frequency: 500000000.0
      gain_imbalance: 0.0
      phase_imbalance: 0.0
      gain_i: 1.0
      gain_q: 1.0
      offset_i: 0.0
      offset_q: 0.0
      inputs:
      - 0
      hardware_demodulation: true
      integration_length: 1000
      threshold: 0.0
      threshold_rotation: 0.0
      time_of_flight: 0
    - id: 1
      outputs:
      - 0
      hardware_modulation: true
      intermediate_frequency: 500000000.0
      gain_imbalance: 0.0
      phase_imbalance: 0.0
      gain_i: 1.0
      gain_q: 1.0
      offset_i: 0.0
      offset_q: 0.0
      inputs:
      - 0
      hardware_demodulation: true
      integration_length: 1000
      threshold: 0.0
      threshold_rotation: 0.0
      time_of_flight: 0
    - id: 2
      outputs:
      - 0
      hardware_modulation: true
      intermediate_frequency: 500000000.0
      gain_imbalance: 0.0
      phase_imbalance: 0.0
      gain_i: 1.0
      gain_q: 1.0
      offset_i: 0.0
      offset_q: 0.0
      inputs:
      - 0
      hardware_demodulation: true
      integration_length: 1000
      threshold: 0.0
      threshold_rotation: 0.0
      time_of_flight: 0
    - id: 3
      outputs:
      - 0
      hardware_modulation: true
      intermediate_frequency: 500000000.0
      gain_imbalance: 0.0
      phase_imbalance: 0.0
      gain_i: 1.0
      gain_q: 1.0
      offset_i: 0.0
      offset_q: 0.0
      inputs:
      - 0
      hardware_demodulation: true
      integration_length: 1000
      threshold: 0.0
      threshold_rotation: 0.0
      time_of_flight: 0
    - id: 4
      outputs:
      - 0
      hardware_modulation: true
      intermediate_frequency: 500000000.0
      gain_imbalance: 0.0
      phase_imbalance: 0.0
      gain_i: 1.0
      gain_q: 1.0
      offset_i: 0.0
      offset_q: 0.0
      inputs:
      - 0
      hardware_demodulation: true
      integration_length: 1000
      threshold: 0.0
      threshold_rotation: 0.0
      time_of_flight: 0
    - id: 5
      outputs:
      - 0
      hardware_modulation: true
      intermediate_frequency: 500000000.0
      gain_imbalance: 0.0
      phase_imbalance: 0.0
      gain_i: 1.0
      gain_q: 1.0
      offset_i: 0.0
      offset_q: 0.0
      inputs:
      - 0
      hardware_demodulation: true
      integration_length: 1000
      threshold: 0.0
      threshold_rotation: 0.0
      time_of_flight: 0
    timeout: 1
    outputs:
    - port: 0
      lo_enabled: true
      lo_frequency: 10000000000.0
      attenuation: 0
      offset_i: 0.0
      offset_q: 0.0
    inputs:
    - port: 0
      attenuation: 0
      offset_i: 0.0
      offset_q: 0.0
    scope_hardware_averaging: true
instrument_controllers:
- type: qblox_cluster_controller
  settings:
    alias: qblox_cluster
    connection:
      type: tcp_ip
      address: 192.168.4.24
    modules:
    - alias: qrm-rf
      slot: 1
    - alias: qcm-rf
      slot: 11
    reset: false
    reference_clock: internal
analog:
  flux_control_topology:
  - flux: phix_q0
    bus: flux_q0_x
  - flux: phiz_q0
    bus: flux_q0_z
digital:
  minimum_clock_time: 4
  delay_before_readout: 0
  topology: []
  gates:
    DRAG(0):
    - bus: drive_q0
      pulse:
        amplitude: 1.0
        phase: 40.0
        duration: 100
        shape: {}
        options: {}
      wait_time: 0
  buses:
    drive_q0:
      line: drive
      qubits:
      - 0
      delay: 0
      distortions: []
      weights_i: []
      weights_q: []
      weighed_acq_enabled: false
